[[normalDict]]
org = '𫚕'
rep = '鰤'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '筿'
rep = '篠'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '𩽾'
rep = '鮟'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '𩾌'
rep = '鱇'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '荘'
rep = '庄'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '滝'
rep = '泷'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '囧'
rep = '窘'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '樫'
rep = '㭴'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '纮'
rep = '弦'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '偾'
rep = '喷'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '哕'
rep = '呕'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '憐'
rep = '怜'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '穂'
rep = '穗'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '砕'
rep = '碎'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '粋'
rep = '粹'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '桜'
rep = '樱'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '長'
rep = '长'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '茑'
rep = '鸟'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '菫'
rep = '堇'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '嗻'
rep = '呜'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '掻'
rep = '搔'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

