[[normalDict]]
org = 'オチンチン'
rep = 'おちんちん'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'チンチン'
rep = 'ちんちん'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'おちんこ'
rep = 'おちんぽ'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'おチンポ'
rep = 'おちんぽ'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '雄チンポ'
rep = 'おちんぽ'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'チンコ'
rep = 'ちんぽ'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'ちんこ'
rep = 'ちんぽ'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'オマンコ'
rep = 'おまんこ'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'マンコ'
rep = 'まんこ'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'アヌス'
rep = '肛門'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'アナル'
rep = '肛門'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'ザーメン'
rep = '精液'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'チ[○●〇]([コチポ])'
rep = 'チン$1'
conditionTarget = ''
conditionReg = ''
isReg = true
priority = 0

[[normalDict]]
org = 'ち[○●〇]([こちぽ])'
rep = 'ちん$1'
conditionTarget = ''
conditionReg = ''
isReg = true
priority = 0

[[normalDict]]
org = 'マ[○●〇]コ'
rep = 'マンコ'
conditionTarget = ''
conditionReg = ''
isReg = true
priority = 0

[[normalDict]]
org = 'ま[○●〇]こ'
rep = 'まんこ'
conditionTarget = ''
conditionReg = ''
isReg = true
priority = 0

