gptDict = [
    {org = "数の子", rep = "鲱鱼子", note = ""},
    {org = "ツッコミ", rep = "吐槽", note = ""},
    {org = "阿鼻叫喚", rep = "凄惨", note = ""},
    {org = "赤ちゃん", rep = "宝宝", note = ""},
    {org = "ドＭ", rep = "抖M", note = ""},
    {org = "幼馴染", rep = "青梅竹马", note = ""},
    {org = "サキュバス", rep = "魅魔", note = ""},
    {org = "ブルマー", rep = "灯笼裤", note = ""},
    {org = "ブルマ", rep = "灯笼裤", note = ""},
    {org = "添水", rep = "竹笕", note = ""},
    {org = "鹿威し", rep = "竹笕", note = ""},
    {org = "チミチャンガ", rep = "恰米强克卷", note = ""},
    {org = "佃煮", rep = "海味蒸", note = ""},
    {org = "オナニー", rep = "自慰", note = ""},
    {org = "ブレンドコーヒー", rep = "混合咖啡", note = ""},
    {org = "オカズ", rep = "小菜", note = "自慰的素材"},
    {org = "アンパン", rep = "夹馅面包", note = ""},
    {org = "勝負パンツ", rep = "决胜内裤", note = ""},
    {org = "抜きゲー", rep = "拔作", note = ""},
    {org = "ライトボックス", rep = "灯箱", note = ""},
    {org = "かたぬき", rep = "挑糕游戏", note = ""},
    {org = "アバズレ", rep = "婊子", note = ""},
    {org = "スズメダイ", rep = "鳃鱼", note = ""},
    {org = "クサフグ", rep = "草河豚", note = ""},
    {org = "ちょんまげ", rep = "发髻", note = ""},
    {org = "かかし", rep = "稻草人", note = ""},
    {org = "恵比寿", rep = "惠比寿", note = "日本的财神、商业之神"},
    {org = "バター犬", rep = "奶油犬", note = ""},
    {org = "ハクビシン", rep = "花面狸", note = ""},
    {org = "サワラ", rep = "马鲛", note = ""},
    {org = "カマイタチ", rep = "镰鼬", note = ""},
    {org = "肉じゃが", rep = "土豆炖肉", note = ""},
]

