allowCloseWhenRunning = false
autoCheckUpdate = true
autoDownloadUpdate = true
autoRefreshAfterTranslate = true
defaultDictOpenMode = 1
defaultNameTableOpenMode = 1
language = "zh_CN"
navigationMode = 0
projects = []
pyEnvPath = "BaseConfig/python-3.12.10-embed-amd64"
themeMode = 0
windowDisplayMode = 1
windowHeight = 691
windowPosX = 20
windowPosY = 32
windowWidth = 1308

[commonGptDicts]
dictNames = ["通用GPT字典", "通用GPT_H字典"]

    [commonGptDicts.spec."通用GPT_H字典"]
    defaultOn = true
    openMode = 1

        [commonGptDicts.spec."通用GPT_H字典".columnWidth]
        0 = 357
        1 = 175
        2 = 425

    [commonGptDicts.spec."通用GPT字典"]
    defaultOn = true
    openMode = 1

        [commonGptDicts.spec."通用GPT字典".columnWidth]
        0 = 284
        1 = 298
        2 = 375

[commonPostDicts]
dictNames = [
    "译后翻译规范",
    "译后生僻字矫正",
    "译后标点修复",
]

    [commonPostDicts.spec."译后生僻字矫正"]
    defaultOn = true
    openMode = 1

        [commonPostDicts.spec."译后生僻字矫正".columnWidth]
        0 = 300
        1 = 217
        2 = 100
        3 = 172
        4 = 75
        5 = 60

    [commonPostDicts.spec."译后翻译规范"]
    defaultOn = true
    openMode = 1

        [commonPostDicts.spec."译后翻译规范".columnWidth]
        0 = 279
        1 = 248
        2 = 100
        3 = 172
        4 = 75
        5 = 60

[commonPostDicts.spec."译后标点修复"]
defaultOn = true
openMode = 1

[commonPostDicts.spec."译后标点修复".columnWidth]
0 = 200
1 = 192
2 = 160
3 = 172
4 = 75
5 = 60

[commonPreDicts]
dictNames = ["译前H统一", "译前H口吃矫正"]

    [commonPreDicts.spec."译前H口吃矫正"]
    defaultOn = false
    openMode = 1

        [commonPreDicts.spec."译前H口吃矫正".columnWidth]
        0 = 311
        1 = 214
        2 = 100
        3 = 172
        4 = 75
        5 = 60

    [commonPreDicts.spec."译前H统一"]
    defaultOn = true
    openMode = 1

        [commonPreDicts.spec."译前H统一".columnWidth]
        0 = 261
        1 = 256
        2 = 100
        3 = 172
        4 = 75
        5 = 60

[showDockWidget]
200 = true

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/Image/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/Image/satan53x.jpg'
detailedText = '从GalGame脚本提取和导入文本'
fromLocal = false
interactiveTips = 'Satan53x'
pathOrUrl = 'https://github.com/satan53x/SExtractor'
subTitle = '草佬味大，无需多盐'
title = 'SExTractor'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/Image/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/Image/gar.png'
detailedText = '神一样的解封包工具'
fromLocal = false
interactiveTips = 'morkt'
pathOrUrl = 'https://github.com/crskycode/GARbro'
subTitle = '无敌了'
title = 'GARbro'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/Image/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/Image/vnt.png'
detailedText = '萌新拯救者一般的文本提取与回封工具'
fromLocal = false
interactiveTips = 'arcusmaximus'
pathOrUrl = 'https://github.com/arcusmaximus/VNTranslationTools'
subTitle = '能少用就少用'
title = 'VNTranslationTools'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/Image/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/Image/crass.png'
detailedText = '早期Galgame解包工具，多看看它的说明文档'
fromLocal = false
interactiveTips = '痴漢公賊'
pathOrUrl = 'https://github.com/shangjiaxuan/Crass-source'
subTitle = '专治老游戏'
title = 'Crass'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/Image/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/Image/sublime.png'
detailedText = '高亮很好使，但编码转换不如emeditor'
fromLocal = false
interactiveTips = 'Sublime HQ'
pathOrUrl = 'https://www.sublimetext.com'
subTitle = '和Em互补长短'
title = 'Sublime'

[[popularCards]]
cardFloatPixmap = ':/GPPGUI/Resource/Image/IARC_7+.svg.png'
cardPixmap = ':/GPPGUI/Resource/Image/revn.png'
detailedText = '别说你是搞机翻的'
fromLocal = false
interactiveTips = 'Dir-A'
pathOrUrl = 'https://github.com/ZQF-ReVN'
subTitle = '拜见祖师爷'
title = 'ReVN'

